- name: Merge provided configuration with device configuration
  cisco.ios.ios_vlans:
    config:
      - name: Vlan_11
        vlan_id: 11
        state: active
        shutdown: disabled
        remote_span: true
      - name: Vlan_21
        vlan_id: 21
        mtu: 9000
        state: active
        shutdown: enabled
    state: merged
- name: Configure the login banner
  cisco.ios.ios_banner:
    banner: login
    text: |
      this is my login banner
      that contains a multiline
      string
    state: present