cluster:
  extraManifests: 
   - https://raw.githubusercontent.com/d3hl/d3-homelab/refs/heads/main/k8s/manifests/install-cilium.yaml 
   - https://raw.githubusercontent.com/d3hl/d3-homelab/refs/heads/main/k8s/manifests/L2Announcement.yaml 
 #  - https://raw.githubusercontent.com/d3hl/d3-homelab/refs/heads/main/k8s/manifests/ip-pool.yml 
   - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
   - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml