- name: add vlans to device
  cisco.ios.ios_vlans:
    config:
      - name: Vlan_13
        vlan_id: 13
        state: active
        shutdown: disabled
        remote_span: true
      - name: Vlan_14
        vlan_id: 14
        mtu: 9000
        state: active
        shutdown: enabled
      - name: Vlan_15
        vlan_id: 15
        mtu: 9000
        state: active
        shutdown: enabled
    state: merged
