- name: Gather listed vlans with provided configurations
  cisco.ios.ios_vlans:
    state: gathered
- name: Merge provided configuration with device configuration
  cisco.ios.ios_vlans:
    config:
      - name: Vlan_11
        vlan_id: 11
        state: active
        shutdown: disabled
        remote_span: true
      - name: Vlan_21
        vlan_id: 21
        mtu: 9000
        state: active
        shutdown: enabled
    state: merged