apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://omni.d3hl.site:8100/
    name: omni-pve-sg-1
contexts:
  - context:
      cluster: omni-pve-sg-1
      namespace: default
      user: omni-pve-sg-1-d3social@pm.me
    name: omni-pve-sg-1
current-context: omni-pve-sg-1
users:
- name: omni-pve-sg-1-d3social@pm.me
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
        - oidc-login
        - get-token
        - --oidc-issuer-url=https://omni.d3hl.site/oidc
        - --oidc-client-id=native
        - --oidc-extra-scope=cluster:pve-sg-1
      command: kubectl
      env: null
      provideClusterInfo: false
