ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_become: true
ansible_become_method: enable
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62656665303461653538616365373234636339616366346661363666323634313764663837376137
          6432316135396161666461343063373066386563396432320a323738633738333836363166663430
          38386366346337326335663364343562393334656135323831666234653861646430326533313739
          3364396561363765360a653463653665353661383661633366666661363466636362393564383265
          3039 