ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_become: true
ansible_become_method: enable
ansible_user: ansible
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34333533346361666533633761363765663465373733643334393535613530306164666236616234
          6161623434633066366162313131623437356638326261300a663764396437383161666361633532
          33353365336338316333373038386466613063636136663738306666363833326231343833663430
          3933643237343731300a313037393438373635623630636137363632343039323135323031393332
          3132