ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_become: true
ansible_user: d3
ansible_become_method: enable
ssh_private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31623037373934623863663861366533336266666136613931633261363133663031646638316536
          6133333034653338383330613838316166396161346232340a626566303361306431333764653338
          63353834373732613366303661376664373366613862663162383462386364336238343966643234
          3761373766303564390a613537313137386236633930643665336461356239613836633934323633
          38373737643832613639613931323237303639623730623137636338396563366461393464353661
          61646661306462356132333436663264396432346337313266623836323437653061323430323939
          33353734646563333032643036653365653263353262373336646536626433386565366162383666
          34353735663433313764333831363334323533633662333130393264663561303965643739643039
          35333735666537376365386634623664336164636662633063366433666438323233613134323661
          38373162623234376538653264383762363133303365303361303263386635343139346131653530
          30663534396165653461643639336562363666303462343933663138316331653534346431346536
          66646265343336636138663733626461336237376664646339323133303835396436383466336562
          38623464666463303463326135656562393636343936306536373861363638303632313636323262
          31613737396461623333396433326564393432623137626131366366393339303564643161616661
          37356465373962386461623638643636333664306331313231306466646638373038323266633462
          39666162336635396364646334343034393531346361653137623363393131383930366332323838
          35353762383763363037376434303132623833313266326264376361376133353861303135613466
          30646665386633333530353361393135663330316533623961383435646562623133646238396435
          32303664353230336132333964633333343231303536623764656135386365363933626535316339
          37366137373232303130353163663833613164393265306566303034633833373939313732323435
          62313436623866303538643038313863643938373237386432326134383439333332336333363534
          38383535616164666331663264343532346366663634396662613961386337303735376137643135
          38346530613264626461383833333866313236653861623061666435313932653565656336356534
          37636335623033613939666236633063623763396536633163303830303631636562333165336135
          62626639313936306163653639643664656330346561373463666135326164303762323039336461
          62653062303133386161326639326435626163323338653434626465393632306136656136383762
          30343431656138346362636362316232656639353166386366646132616234326234373938653766
          37356138356465313064656439653733323030396532303234383638313134336264316562633966
          39663563613166643235303932373032643562623933393166613964366439646436313164393935
          63643737663033366334303461306538353038383762666165313965313931313732373262373833
          62643730636265306134376162626638336531373664303932653830363133396231663937386561
          61303532303836343739663262636664383533326431306634356365636536306464666330393238
          64313039386164626237393763633263353562386263323233623332616536653332313336393138
          65313032373962353839646662336165316431386135666335333332383266343836333666393137
          31313036373136386566623037636538616264363034373036616436663631323034316238663239
          63376263393764383434346339343934393463376338616463323463623564346237633730316365
          36343632653533656561323535313735656135613737313332613238306236653931373165326663
          32633030353233633637616262363630663839643431386166656661393931346230343633633466
          34393837653431363831303936666663623966323566666665303135313836313437316434376362
          36393462383363653464623138393339393435326233306139626465633365386531373038333732
          39316262353435343833666564663763326235383366626237656336363439376362643163616636
          65646237366330663239653166383231663737373835313733343361373261613838336364613063
          65376536616432346666373736333366393433393131636234663135376239666332383833663864
          38656563383038333230326461323032656366623263326132626439376364643434613234633834
          30333638383064393461643039653034356634313434316163386130346262303533333065663432
          37356566633263356131643062383839363366613666653739636537383466373330323466383437
          63613431653564356538376236303634383963366362313730363533616435363635643336626663
          63383266636566343664663265333063656637623063626166376131393262623364616363383335
          38396365666337356337626337343730656665306232386264333731363436313063373162653062
          39343838396365613864396464383536323063336464373366643039613130353131346266633232
          31663936386363656663306164383865663136663031613936373138636433313730613338613563
          65383663633135653963636236626430353537366264386639393963396531633430613337396335
          66396430363066373163373137386233303636323634363232326238623435363539303465656534
          36306134653964656234303132336661393730313066323463663764323166373262323938326237
          31333530323862323237343466633931303937306531643664313162636462613931623662373937
          36386439393361313937353664633834386130346434626330613238363433626165356538653962
          31373065323234313134623630613039616265373033396464346433636339386264363430643263
          30393534336231393737343637633566666534376635313036383635383035356361303730386364
          31356232353764363231323233376632333233626535636134343138643934383235643031636139
          62643532316538333730353063363838626133653764643032653430663334326335363837613335
          31386666646565333263353162326333356238306537653832616331613531343035346565306331
          36663033373332396639323461623733636263393664643438353630366532613465303833653331
          39393830613637633732653433643737383335613034383461306266313362646631373634656134
          61363937343132353765373931353231376330616636393735303431633838626532626232306632
          35323330633936303764636435666537336638393531646534303733653930316334353535633437
          63313866303037383461386237303963656230663531376137333662326564636561633438336363
          61613938303739663265333439383062363937616430363235313663373262646431656462383336
          33653138353163666161656562346264316364666530303263623862653634383535616363353534
          64653137353462323439356466346361306564666139663030396336393635613539373938623333
          30366235363737313237353633386232363732376336353733396263373662663561353163383737
          36386335373135656462363363376263656161633830646536346164396566333631643661316633
          30383139363832356237663030366637333932336137656561613730363030386632373962633063
          37393961393336343963363663646661343735623163383764646336623730633739333838666562
          61343739316331316334363634366266386230306538643261383837336138316361323033323139
          31393335663638326431636663626264633065616361316165633963313864643539326239623539
          39373338646136613535343836666130616434633230353439396430383236373762353131613232
          37333164633866353532663439393136653465323664383939626337653164376339616533653430
          61366132663164636339666335343061313163306365303839333065353661623637656334646465
          36353438306263303231616563383066663834623533666239636364633464303365323638373165
          32353061303033396633316432363462393463333335356139313164643134373230386137633866
          36396563363935393233303266626661393735373132633961643439656638666231643036646535
          61353634636337626234363964636263323535396266653664363736643036643436343330303338
          61626639656335373934646161626332393862353265356530396337613437656461633935663233
          31616565646330613330343963663637653037386532633463633165353630306631323266663263
          37313663353866306236616163316239316633623933393865636264623036316138383339303638
          65656362653937366132643533653362666236666634613034623733383031323661656234333636
          31336331356133336563336431373138613261633364663162383131363064616166396164653362
          32326338343033373661633639373034346637613530343030326534303264636463333536646135
          35303961396262316635326132616436626132396636363031353863613233323466376361326537
          35616265313561326464636665613236616461356139336562633135356337353061633135363132
          34613935626534616232373634626532396231396639383936383361393535636631333461626665
          32393135353635346565653265353861386438383036353434346661613537346466323534633835
          61333864366163656266613835663738636637366331386332626435666338343230633664333164
          65623630333635313661316638336266333363666164636532326564366631653238636135343430
          66326631326232653238626537623963363962653765393965353662666465383039303964303536
          34386631636565353633366361366162346562376333393534346536306236613837633162353935
          35383938616665636336653866313361393835386461346232323234353035633765613038663537
          34646231373862393039383433623434306561626266376361343537343435653135383064323731
          64393764323365623636363462373665333864643236336139613964646362373036323534636633
          31386433353563393639386232646235626536326332636464383639666464623263656435393235
          32396439326238366330316461653739643334323664353464636238376564333761656337653332
          34613764333665353931376661616232326537623266626463376239656639393638353939663464
          30353064363838353631336131343662303335323030616337356331636464383966646166616565
          32663339376436356430383830623932373466666662356630363366386565636561316539383031
          61646338376164333139313566343263643761343232316335646331616236663432353538346265
          38353666616133326562623336643232313235636166663338623737386337356565616462303634
          33303364373239663637653636353161333131306164653066343134383037653935653834663635
          64613566333538653832366235363934333162356431636566343134633335393032356237313638
          33376136313265636564653435363062303630336639643730366464663430313631633037636635
          34623635633734303734666162306263623439623836646231383365623630383435626430623161
          32623337306239646361393233626232653034613030623064313062333261613833386537313331
          30616437366433653966623163656364303533666663396133383539343731316266323662306162
          32333466663636366366666134316563356165323537333563346336333863373964363063616634
          35333133643866343039343965306434306237623862396133613134326465326464356236376238
          65616661323631663032666633346463316335303462336166323936633865393139323566646264
          63656264663634623162663932316164346130656163306562313137613265366631383935633436
          63316461316133613465346635366133336565666161343637386538323639653238376630366334
          66306564333365646262353035333730303230616134313133313034643464333332303736636330
          39396638366235643632333236633362333033613338386364393136643063623831646536633230
          31313936376563373735303437303834633838653934636637653736346565303962616534646439
          61653134373632386665306537306466613632633366326662656435343166316332363263316132
          39613037383638623731666331656161633937386232646264303665376266383133363334306137
          35373361613030633566336161396132303164366534643866376234656661666534316238653236
          64633063633832333230643361313130613939633064383438373237333365613934373961326331
          32656631393166343166373065633566653231653936363931383030393161336630316564646662
          39383636636333616535313437353432373937636463663336663465616338666235626638323437
          66386634393938356631613139383432356362626330393934326162343265656234653661623830
          32326434333462306531653632353736656661333232386464363863613066636235356233393138
          66343534343836656566643963663765336538336336613234396462373639613663343735373532
          63363461313430323839383337383736373737613331333861373237633162396539366336626638
          62376537356538656664306166613764303263356130383936376464323235656238356134393735
          63323138343634383332373765363037376234643830656537336462373237643839646635626236
          63663436346533383437353061303734396662646630303161633535386336616435646664623365
          30333766366632636632636638636130396264666535323039393063303861313766623731366534
          33663061613661393464663966353936666165326238373233356435363530623334643061633465
          30356332376638326661303535323334613964663063343230376235656638323038336561613965
          39373538316333333163353430396131636362663462653933613638316364376462646164343164
          35383963333163383238656535613465386431343731303132333964623032613239373362633835
          62336237636665366465376566363166326532343463636538653663663466663434666363313764
          34303963653262356138393464353061653631323034626263653461303235653032633063373261
          63333235316434343164633135626364646162616239646437366566643338396136303333333330
          35393436333237356539666566393763653635656530303861643232643062393035303063366164
          62373365643937643062383837343035353237373961643333616131306463353764333138333838
          64656135343733643332333035663533663761353536626130626163323363666337306663396664
          62396232626137373061333339646363633164356461643865653636333763383534373333666265
          33383366613366663038306466353934376665313038643465323533383463653365666662373532
          38323431353366383036323162353739646265326331386434306638333761386162656561663031
          32613433616265393163393930343965393832663732393665373764363862326239366635326265
          36383432613764373434353061366237656662306362313966373166626539313161626565633230
          39383635393036346635646333323031613530386132386436656335346361306332326134626364
          30373239653363363832643863663365626331343163303530666233303635376564386566643636
          35326233623633393835646133363361636136303032613537363739666531333138626432316431
          66633530396430646162356137373665316332326163366334383134303962623832643136653737
          35316535626365643262326130336337633435333265643665343665366331666664373966653633
          31653231623361663065626331343136373364663831643237643835343264353430643732343035
          32383639653732383863353936373264356561333734383664633861613935633238393562633863
          34653333396539623431656266623263376361623631626432356365646565336238643266333433
          63343934626637623363633733656138383166636363313866613534363266396663376262666463
          66353863316562626263663631643238376430316431363432636237633633333335373432393863
          62626534616236373639343862643964396631633135366539633263666134383839303036646666
          32353236636564383535633064313832623635643937626431393834363165313337396331633131
          37396638313439663962313432386233313630643633383733303838333565666165633262643762
          34363738656330643130343931653163306262633933643733356434623337656239303732323931
          63663736363736616234656662343662346432336530663532396136636535353136663233393738
          37353230323034663331633337313866613736666333343364663734646465373032653137313166
          34393031656466396538353162383939393134303739633934376530643831636336343361663535
          62343261363365626331313766346165653837653237633239653863623830636535313831303265
          63393765613032646230383634666666633263306531626232613433373366333831333966656364
          62333237356161383835326366663662373930663538313831383864356331613235366634636432
          35363862646163613562386430323332666464653435623935393839333437343630666231346236
          35653339396336393838386531386133376263373131303562636130643330336531386163356339
          33306434373064623633