ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_become: true
ansible_become_method: enable
ansible_user: d3
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64316566386462656633613038363664656430306465346334366566353134623130333834343231
          6631346632373261626237656332353935656262303532610a346236346664633264323439613635
          39653366313535353135663462393263386135336137333262326336313339663566336461366338
          3433383130653464620a343837353039306663656663326232333736656362393563346334306139
          3961