ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_user: d3
#ansible_password: !vault |
#  $ANSIBLE_VAULT;1.1;AES256
#  31633234313964366437373566326239646332306535323365643738346231383230613439666666
#  6236643264613336313664363561396133626437663061360a653761373237663534626231363735
#  64306637303931383636333661616266336564333665313664643036353466383439303835666639
#  3664336263303032300a366566636162373037316265613564383866386631356265343333373761
#  6464
ansible_become: true