- name: Manage Komodo Service
  hosts: komodo
  roles:
    - role: bpbradley.komodo
      komodo_action: "install"
      komodo_version: "latest"
#      komodo_passkeys: 
#        - !vault |
#          $ANSIBLE_VAULT;1.1;AES256
#          33346138386538663433316331386233306235386363323261656138323131356139333265353166
#          6132663733633231313035333765653063363431336461330a643631383336383266343932323139
#          63326136613636643833303362666639386164343137396365313933326566343131353062653031
#          3565356335373835320a373461636563393936386135353464333632356233353661643533376536
#          39343561666465383162623935323261636362616132346664376239653765393034336566363336
#          30373934393032333130316261343738613236386139616537333263663836303330656662376162
#          64376165633164633963316130323236393530303337376165383363653064383963336534313132
#          34393731373862663164