name: Deploy with Ansible 2
on:
  #pull_request:
  #  branches:
  #    - main
  push:
    branches:
      - cisco
 #  types: [closed]

jobs:
  deploy:
    name: Deploy Ansible Playbook
   # if: github.event.pull_request.merged == true
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          echo "${{ secrets.CISCO_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i ansible/inventory/hosts.ini ansible/playbooks/IOS-XE/10.10.10.1.yaml --private-key private_key.pem -u ${{ secrets.ANSIBLE_USER }} 